version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=boabatch2jun2023customerdb
    volumes:
      - /data/mysql
    healthcheck:        
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - boanetwork
  customer-app:
    image: customerapp
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
       #- 8060-8070:7070
        - 7074:7074
    volumes:
      - /data/compose-app

    networks:
      - boanetwork
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - boanetwork


  grafana:
      image: grafana/grafana
      #command:
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
      restart: always
      ports:
        - 3000:3000
      networks:
        - boanetwork
### put all the networks here
networks:
  boanetwork:
      external: true